export enum RoomEvent {
  CREATE_ROOM = 'create-room',
  PLAYER_STATE_UPDATE = 'player-state-update',
  JOIN_ROOM = 'join-room',
  PLAY = 'play',
  PAUSE = 'pause',
  SEEK = 'seek',
  SKIP = 'skip',
  ADD_TO_QUEUE = 'add-to-queue',
  FORCE_PLAY = 'force-play',
  REORDER_QUEUE = 'reorder-queue',
  REMOVE_FROM_QUEUE = 'remove-from-queue',
  SEND_DANMU = 'send-danmu',
  SEND_MEME = 'send-meme',
  QUEUE_UPDATED = 'queue-updated',
  ROOM_JOINED = 'room-joined',
  CLIENT_COUNT_UPDATED = 'client-count-updated',
  CMD_PLAY = 'cmd-play',
  CMD_PAUSE = 'cmd-pause',
  CMD_SEEK = 'cmd-seek',
  CMD_SKIP = 'cmd-skip',
  DANMU = 'danmu',
  MEME = 'meme',
}
